### ISSUE TITLE
Alpha bug: Find command should only display either owner or pet list

### ISSUE THREAD

**Issue by naythee169** [AY2425S1-CS2103T-T13-3/tp#136]
Upon successful useful of the find command to find an owner or pet, only one of the owner or pet lists should be displayed, not both as seen below

![Screenshot 2024-11-05 at 3 51 58 PM](https://github.com/user-attachments/assets/2bd2ebee-1d46-4f82-8bd0-7e26e4af3d93)

**Comment by jloh02** [comment]
Closing this in favor of #116
