### ISSUE TITLE
[PE-D][Tester C] First sample commands don't work due to duplicate IC number already existing 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-3/tp#200]
In the second sample command given on page 2, you give an example of adding somebody. Unfortunately, in the users that load when you open the app for the first time, a user with the IC that you specified already exists, so the command doesn't work. Perhaps it may be best to put a command where the person doesn't already exist

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: rahula1008/ped#5

**Comment by jloh02** [comment]
TODO: First task for getting started should be to clear all data
