### ISSUE TITLE
[PE-D][Tester A] `List` command unable to be executed.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-3/tp#207]
To replicate the bug, 

1. Type in `list OWNERS` in the CLI.

2. The error message says that `lists owners or pets in the address book whose relevant fields contain the specified keywords **(case-insensitive)** and displays them as a list with index numbers.`

This means that it should work because OWNERS should be read as owners.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Teddayz/ped#3

**Comment by jloh02** [comment]
Feature flaw. To be fixed in future iterations
