### ISSUE TITLE
[PE-D][Tester C] The Edit Parser allows non Singaporean phone numbers when UG says "Singapore phone standards"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-3/tp#210]
Singaporean phone numbers typically begin with either 6(for home numbers) or 8 or 9 for private handphones. I was able to edit one of the owners to have the phone number: 77777777

![Screenshot 2024-11-08 at 4.45.18 PM.png](https://raw.githubusercontent.com/rahula1008/ped/main/files/b59fb287-307b-4694-b3eb-7420885a21fa.png)

Refer to owner 7 in the image and the bot response given.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rahula1008/ped#8

**Comment by jloh02** [comment]
Past history has shown various starting numbers being allowed by the Singapore government for specific purposes (e.g. phone numbers starting with digit 3 for VOIP). As such, all 8-digit numbers was chosen to be allowed.

TODO: Update user guide to indicate all 8 digit numbers allowed
