### ISSUE TITLE
[PE-D][Tester E] Irregular white lines in UI after entering a valid link command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-3/tp#212]
Cosmetic issue with UI: After entering a valid link command, the UI displays the following result with irregular white lines:
![image.png](https://raw.githubusercontent.com/yxtan02/ped/main/files/fe91ca8d-bed2-44c3-a16c-3925131e3463.png)

I raised this up as the UI of the app differs from what was shown in the UG:
![image.png](https://raw.githubusercontent.com/yxtan02/ped/main/files/725f4ddf-b780-460d-bd5f-56fc0af7ab4f.png)

Would be good to update the screenshot to reflect the actual UI of the app to ensure consistency and prevent user confusion

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: yxtan02/ped#5

**Comment by clarissatjx** [comment]
this might be their computer issue, works fine even on my own monitor?

![Screenshot 2024-11-11 at 6 12 07 PM](https://github.com/user-attachments/assets/83ec86c1-8c5e-4423-b10d-81ff1f900bf1)

**Comment by clarissatjx** [comment]
if no one oppose ill close this issue near 2359

**Comment by jloh02** [comment]
appears on mine too. raised before but idk how to fix. ngl don't need to report

**Comment by clarissatjx** [comment]
ok fire
