### ISSUE TITLE
[PE-D][Tester B] GUI cannot display long tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-3/tp#218]
## Describe the Bug

When adding tags to pets, a sufficiently long string will cause the GUI to be unable to display the entire tag.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: amoschee/ped#5

**Comment by jloh02** [comment]
Tags not meant to be long

TODO: Update user guide to advise against longer tags
