### ISSUE TITLE
[PE-D][Tester E] Mistakes/Syntax issues in error message for unlink command.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-3/tp#219]
When entering an invalid unlink command, the following error message is shown:
![image.png](https://raw.githubusercontent.com/yxtan02/ped/main/files/1a1f0282-289e-4b5a-aea8-273ae250dadb.png)

The error message states that the format for the unlink command is “unlink OWNER_INDEX [t/PET_INDEX]...” This is inconsistent with the format stated in the user guide where **there is an “o” before the OWNER_INDEX**. Also the error message **puts t/PET_INDEX within square brackets, which should not be the case as t/PET_INDEX] is not optional**

Suggestion:
Edit the error message to be consistent with the format stated in the UG:
![image.png](https://raw.githubusercontent.com/yxtan02/ped/main/files/5a7671db-8e1d-4b02-9784-0ed18947ce63.png)

Steps to reproduce:
1. Enter "unlink"

Expected:
An error message that states that the correct format should be "unlink oOWNER_INDEX t/pPET_INDEX…"

Actual:
An error message with syntax differing from the UG

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yxtan02/ped#7

**Comment by jloh02** [comment]
Standardizing of text not allowed
