### ISSUE TITLE
[PE-D][Tester A] Pets with no owners. (General comment)

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-3/tp#233]
There might be a lot of confusion in the PawPetrol if pets are not linked to their owners from the get-go. Especially when pets are allowed to have duplicate names, this makes it confusing for your users to properly keep track of their owners and pets. 

Might want to force a pet upon creation to have an owner. (Meaning you have an owner contact created beforehand)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Teddayz/ped#10

**Comment by jloh02** [comment]
TODO: Advice in UG to always link pet to owner as first action though not enforced
