### ISSUE TITLE
[PE-D][Tester E]  UI displays non-matching owners when executing a find pet command.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-3/tp#236]
When executing a find pet command, all owners will be shown even though they are not pets and do not match the given keyword. I believe that after executing a find pet command, the UI should only show pets with no owners at all to prevent user confusion.

For example, let's say I have an owner and a pet: 
![image.png](https://raw.githubusercontent.com/yxtan02/ped/main/files/888703c5-75c4-481b-b6d8-4567f98d6818.png)

When I execute the command "find pet n/Fluffy", I get the following result where the owner is shown together with the matching pet
![image.png](https://raw.githubusercontent.com/yxtan02/ped/main/files/1e5c1fc4-2ba7-4362-b984-9926c176659c.png)

Suggestion: Ensure that no owners are displayed in the UI after a find pet command is executed.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yxtan02/ped#10

**Comment by jloh02** [comment]
Intended. To update UG to say
1. Only list of find will update, other list does not change
2. Possible to enter find pets then find owners
