### ISSUE TITLE
[PE-D][Tester E] Unable to find owner based on fields such as phone, email, address

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-3/tp#241]
Currently, the find command only allows user to search for owners based on their name. However, there are also scenarios where veterinary clinics need to search for owners based on their phone, email, address. For example, when an owner emails the clinic, the clinic would have find that owner based on the email.

You may consider putting this down in your proposed improvements section in your DG to prevent this feature flaw from being raised in the actual PE.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yxtan02/ped#11

**Comment by jloh02** [comment]
Feature request
