### ISSUE TITLE
[PE-D][Tester D] Duplicate pets

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-3/tp#250]
Able to add two pets that have the same variables 

Example:
- pet n/Fluffy s/Dog b/Golden Retriever a/5 x/F t/playful t/cute
- pet n/Fluffy s/Dog b/Golden Retriever a/**05** x/F t/playful t/cute

Both get accepted into the system although all the variables are essentially the same
- Other than the extra 0 in the age variable for the second add pet command 

![image.png](https://raw.githubusercontent.com/thenosewizard/ped/main/files/fd8abeaa-d561-443b-b5d2-a982954a86ed.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: thenosewizard/ped#6

**Comment by jloh02** [comment]
Intended behavior but age should be truncated
