### ISSUE TITLE
[PE-D][Tester A] Error message for `edit` command too cluttered

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-3/tp#256]
By inputting the wrong command, there are many different messages for this one command.
![image.png](https://raw.githubusercontent.com/Teddayz/ped/main/files/68688451-e5e1-4baa-ac6c-c7b51ea369ab.png)

Perhaps you could split the error message to make it clearer to users as to what went wrong with their input.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Teddayz/ped#16

**Comment by jloh02** [comment]
Does not affect user directly but good to have enhancement
